elasticsearch:
  image: es
  container_name: elasticsearch
  ports:
    - 9200:9200
  environment:
    CLUSTER_NAME: "es"
    NODE_NAME: "node0"
    NODE_RACK: "es1"
logstash:
  build: logstash/5.0.0
  container_name: logstash
  environment:
    TIMEZONE: "Asia/Tokyo"
    ADDR_IPV4: "192.168.0.250"
    ADDR_IPV6: "240d:1a:158:2900::100"
  ports:
    - "5514:5514/udp"
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch