elasticsearch:
  build: es
  container_name: es
  ports:
    - 9200:9200
logstash:
  build: logstash
  container_name: logstash
  ports:
    - 9514:9514
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch