elasticsearch:
  build: elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200
logstash:
  build: logstash/5.0.0/Dockerfile
  container_name: logstash
  ports:
    - "5514:5514/udp"
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch