elasticsearch:
  build: elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200
fluentd:
  build: fluentd
  container_name: fluentd
  ports:
    - 5514:5514
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch