elasticsearch:
  image: airforon/elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200
  environment:
    CLUSTER_NAME: "es"
    NODE_NAME: "node0"
    NODE_RACK: "es1"
  volumes:
    - ~/data/elasticsearch:/usr/share/elasticsearch/
fluent:
  build: fluent
  container_name: fluent
  environment:
    TIMEZONE: "Asia/Tokyo"
    HOSTNAME: "air-foron.com"
  ports:
    - "5140:5140/udp"
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch