elasticsearch:
  build: elasticsearch
  container_name: elasticsearch
  ports:
    - 9200:9200
fluentd:
  build: fluentd
  container_name: fluentd
  ports:
    - 24224:24224
  links:
    - elasticsearch
kibana:
  build: kibana
  container_name: kibana
  ports:
    - 9204:5601
  environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
      - elasticsearch
nginx1:
  build: nginx
  container_name: nginx
  environment:
      HOSTNAME : "docker-2-3.air-foron.com"
  ports:
    - 80:80
  log_driver:
    fluentd
  log_opt:
    fluentd-address: localhost:24224
    fluentd-tag: raw.docker.{{.Name}}.{{.ID}}